<?php
/*
 | Regenerate Android launcher icons from the Saint Globle logo.
 |
 | capacitor/android/ is git-ignored (regenerated by the Capacitor CLI), so the
 | mipmap icons are not tracked. Run this after `cap sync android` / any time the
 | native project is recreated, so the app icon stays the logo:
 |
 |     e:/xampp/php/php.exe capacitor/scripts/gen-icons.php
 |
 | Source: public/images/logo.png (512x512, full-bleed brand logo).
 */

$root = dirname(__DIR__, 2);                       // project root
$src = "$root/public/images/logo.png";
$resDir = "$root/capacitor/android/app/src/main/res";

if (! is_file($src)) {
    fwrite(STDERR, "Logo not found: $src\n");
    exit(1);
}

$logo = imagecreatefrompng($src);
$sw = imagesx($logo);
$sh = imagesy($logo);

// mipmap dir => [legacy square px, adaptive foreground px]
$dens = [
    'mipmap-mdpi' => [48, 108],
    'mipmap-hdpi' => [72, 162],
    'mipmap-xhdpi' => [96, 216],
    'mipmap-xxhdpi' => [144, 324],
    'mipmap-xxxhdpi' => [192, 432],
];

function scaled($logo, $sw, $sh, $n) {
    $img = imagecreatetruecolor($n, $n);
    imagealphablending($img, false);
    imagesavealpha($img, true);
    imagecopyresampled($img, $logo, 0, 0, 0, 0, $n, $n, $sw, $sh);
    return $img;
}

// Square logo with a circular alpha mask (legacy round icon).
function roundIcon($logo, $sw, $sh, $n) {
    $base = scaled($logo, $sw, $sh, $n);
    $out = imagecreatetruecolor($n, $n);
    imagealphablending($out, false);
    imagesavealpha($out, true);
    imagefill($out, 0, 0, imagecolorallocatealpha($out, 0, 0, 0, 127));
    $c = ($n - 1) / 2.0; $r = $n / 2.0;
    for ($y = 0; $y < $n; $y++) {
        for ($x = 0; $x < $n; $x++) {
            if ((($x - $c) ** 2 + ($y - $c) ** 2) <= $r ** 2) {
                imagesetpixel($out, $x, $y, imagecolorat($base, $x, $y));
            }
        }
    }
    imagedestroy($base);
    return $out;
}

foreach ($dens as $dir => [$sq, $fg]) {
    $path = "$resDir/$dir";
    foreach ([
        ['ic_launcher.png', scaled($logo, $sw, $sh, $sq)],
        ['ic_launcher_round.png', roundIcon($logo, $sw, $sh, $sq)],
        ['ic_launcher_foreground.png', scaled($logo, $sw, $sh, $fg)],
    ] as [$name, $img]) {
        imagepng($img, "$path/$name");
        imagedestroy($img);
    }
    echo "$dir: launcher {$sq}px, foreground {$fg}px\n";
}

// Adaptive background = the logo's own blue, so foreground-scaling launchers blend.
$c = imagecolorat($logo, 2, 2);
$hex = sprintf('#%02X%02X%02X', ($c >> 16) & 0xFF, ($c >> 8) & 0xFF, $c & 0xFF);
file_put_contents(
    "$resDir/values/ic_launcher_background.xml",
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<resources>\n    <color name=\"ic_launcher_background\">$hex</color>\n</resources>\n"
);
echo "ic_launcher_background => $hex\n";

// --- Splash screen (the "fresh screen" shown while the app boots) ---------
// Launch theme uses @drawable/splash; render the logo centred on the brand
// blue for every density (portrait + landscape) plus the base drawable.
[$br, $bg, $bb] = [($c >> 16) & 0xFF, ($c >> 8) & 0xFF, $c & 0xFF];

function splash($logo, $sw, $sh, $w, $h, $br, $bg, $bb) {
    $img = imagecreatetruecolor($w, $h);
    imagefilledrectangle($img, 0, 0, $w, $h, imagecolorallocate($img, $br, $bg, $bb));
    // Logo ~42% of the shorter side, centred.
    $d = (int) round(min($w, $h) * 0.42);
    imagealphablending($img, true);
    imagecopyresampled($img, $logo, (int) (($w - $d) / 2), (int) (($h - $d) / 2), 0, 0, $d, $d, $sw, $sh);
    return $img;
}

$splashes = [
    'drawable' => [512, 512],
    'drawable-port-mdpi' => [320, 480], 'drawable-land-mdpi' => [480, 320],
    'drawable-port-hdpi' => [480, 800], 'drawable-land-hdpi' => [800, 480],
    'drawable-port-xhdpi' => [720, 1280], 'drawable-land-xhdpi' => [1280, 720],
    'drawable-port-xxhdpi' => [960, 1600], 'drawable-land-xxhdpi' => [1600, 960],
    'drawable-port-xxxhdpi' => [1280, 1920], 'drawable-land-xxxhdpi' => [1920, 1280],
];
foreach ($splashes as $dir => [$w, $h]) {
    $path = "$resDir/$dir";
    if (! is_dir($path)) {
        mkdir($path, 0777, true);
    }
    $s = splash($logo, $sw, $sh, $w, $h, $br, $bg, $bb);
    imagepng($s, "$path/splash.png");
    imagedestroy($s);
}
echo "splash screens rendered (logo on $hex)\n";

// Android 12+ splash uses the platform API, not the background drawable. Write a
// values-v31 launch theme so the boot screen shows the logo on the brand blue.
$v31 = "$resDir/values-v31";
if (! is_dir($v31)) {
    mkdir($v31, 0777, true);
}
file_put_contents("$v31/styles.xml", <<<'XML'
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Android 12+ platform splash: logo on brand blue (see gen-icons.php). -->
    <style name="AppTheme.NoActionBarLaunch" parent="Theme.SplashScreen">
        <item name="android:windowSplashScreenBackground">@color/ic_launcher_background</item>
        <item name="android:windowSplashScreenAnimatedIcon">@mipmap/ic_launcher</item>
        <item name="postSplashScreenTheme">@style/AppTheme.NoActionBar</item>
    </style>
</resources>

XML);
echo "values-v31/styles.xml written\nDONE\n";

imagedestroy($logo);
